/* DO NOT EDIT, AUTOGENERATED FROM gui.py */

static constexpr int        SUBSTRATE_TEMP        = 460;
static constexpr int        SUBSTRATE_TEMP_OFFSET = 15;
static constexpr double     SUBSTRATE_KP          = 0.02;
static constexpr double     SUBSTRATE_KD          = 0.40;

static constexpr int        SOURCE_TEMP           = 460;
static constexpr int        SOURCE_TEMP_OFFSET    = 15;
static constexpr double     SOURCE_KP             = 0.02;
static constexpr double     SOURCE_KD             = 0.40;

static constexpr long       DEPOSITION_TIME_MS    = 1800000;
